# Generated by Django 4.1.7 on 2023-03-20 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ITunesCategory",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=255)),
                ("term", models.CharField(max_length=255)),
                ("scheme", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Value provided by iTunes RSS feed",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("artist_url", models.URLField(null=True)),
                ("release_date", models.DateField()),
                ("track_count", models.IntegerField()),
                ("rights", models.CharField(max_length=511)),
                ("itunes_link", models.URLField()),
                (
                    "itunes_price_dollars",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "image_1_url",
                    models.URLField(help_text="I have nothing to apologize for"),
                ),
                ("image_1_height", models.IntegerField()),
                ("image_2_url", models.URLField()),
                ("image_2_height", models.IntegerField()),
                ("image_3_url", models.URLField()),
                ("image_3_height", models.IntegerField()),
                (
                    "itunes_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="top_albums.itunescategory",
                    ),
                ),
            ],
        ),
    ]
