# Generated by Django 4.1.7 on 2023-03-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("top_albums", "0002_top_album_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="image_1_height",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="image_1_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="image_2_height",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="image_2_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="image_3_height",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="image_3_url",
            field=models.URLField(null=True),
        ),
    ]
